### ISSUE TITLE
Disable support for multiple dealer types

### ISSUE THREAD

**Issue by NerdyTherapist** [MateMonkey/api#2]
The documentation states 

> type can be any combination of ['bar', 'club', 'retail', 'restaurant', 'other', 'hackerspace', 'community'] separated by commas, e.g. type=retail,club

Since this is not offered by the website (so there should not yet be dealers with multiple types) and imho is much more convenient to make the user choose only one (again, as it is done on the website), I suggest removing this feature.

**Comment by mguentner** [comment]
Hey :)

You _can_ select multiple dealer types in the frontend. Here are bars and clubs in Munich:
https://matemonkey.com/map/dealer/?@=14,48.136566,11.582465&types=bar,club

Have a look at the selection bar in the top-left corner. Try selecting another type or switch back to 'all' dealers by clicking on :eight_spoked_asterisk:

**Comment by NerdyTherapist** [comment]
Hi,

I just realized I was looking at the wrong request type. Of course I can `GET` multiple dealer types, but I wrongly thought it was possible to `POST` multiple dealer types. 

My bad, sorry!

PS: I'll send you an email with some questions regarding my iOS app for MateMonkey when development has progressed a little more (yes, that's me making all the requests to the Test API :wink:).
